
    create table CandidacyJPA (
        id varchar(255) not null,
        primary key (id)
    );

    create table CandidacyJPA_CandidateJPA (
        CandidacyJPA_id varchar(255) not null,
        candidates_id varchar(255) not null,
        primary key (CandidacyJPA_id, candidates_id),
        unique (candidates_id)
    );

    create table CandidateJPA (
        id varchar(255) not null,
        firstName varchar(255),
        lastName varchar(255),
        candidacy_id varchar(255),
        primary key (id)
    );

    create table ElecteurJPA (
        id varchar(255) not null,
        primary key (id)
    );

    create table PropositionJPA (
        id varchar(255) not null,
        text VARCHAR(1000000),
        candidacy_id varchar(255) not null,
        tagLevel1_id varchar(255),
        primary key (id)
    );

    create table PropositionJPA_TagJPA (
        PropositionJPA_id varchar(255) not null,
        tags_id varchar(255) not null,
        primary key (PropositionJPA_id, tags_id)
    );

    create table QuestionJPA (
        id bigint generated by default as identity (start with 1),
        rightAnswer boolean not null,
        text VARCHAR(1000000),
        candidacy_id varchar(255),
        candidate1_id varchar(255),
        tagLevel1_id varchar(255),
        primary key (id)
    );

    create table ResponseJPA (
        id bigint generated by default as identity (start with 1),
        correct boolean not null,
        occurence integer not null,
        username varchar(255),
        electeur_id varchar(255),
        question_id bigint,
        primary key (id)
    );

    create table StatsCandidacyJPA (
        id bigint generated by default as identity (start with 1),
        answered integer not null,
        rights integer not null,
        candidacy_id varchar(255),
        primary key (id)
    );

    create table StatsThemeJPA (
        id bigint generated by default as identity (start with 1),
        answered integer not null,
        rights integer not null,
        tag_id varchar(255),
        primary key (id)
    );

    create table TagJPA (
        id varchar(255) not null,
        level integer not null,
        name varchar(255),
        namespace varchar(255),
        primary key (id)
    );

    create table UserStatsJPA (
        id bigint generated by default as identity (start with 1),
        idUser varchar(255),
        primary key (id)
    );

    create table UserStatsJPA_StatsCandidacyJPA (
        UserStatsJPA_id bigint not null,
        statsCandidacy_id bigint not null,
        unique (statsCandidacy_id)
    );

    create table UserStatsJPA_StatsThemeJPA (
        UserStatsJPA_id bigint not null,
        statsTheme_id bigint not null,
        unique (statsTheme_id)
    );

    alter table CandidacyJPA_CandidateJPA 
        add constraint FKA17D20E46ADE0FC7 
        foreign key (CandidacyJPA_id) 
        references CandidacyJPA;

    alter table CandidacyJPA_CandidateJPA 
        add constraint FKA17D20E4CD8F0ACF 
        foreign key (candidates_id) 
        references CandidateJPA;

    alter table CandidateJPA 
        add constraint FK41D24B783ADE8F72 
        foreign key (candidacy_id) 
        references CandidacyJPA;

    alter table PropositionJPA 
        add constraint FK197D2545F86CEDC1 
        foreign key (tagLevel1_id) 
        references TagJPA;

    alter table PropositionJPA 
        add constraint FK197D25453ADE8F72 
        foreign key (candidacy_id) 
        references CandidacyJPA;

    alter table PropositionJPA_TagJPA 
        add constraint FK715E3E3BCE3BE9AF 
        foreign key (tags_id) 
        references TagJPA;

    alter table PropositionJPA_TagJPA 
        add constraint FK715E3E3BE77DE347 
        foreign key (PropositionJPA_id) 
        references PropositionJPA;

    alter table QuestionJPA 
        add constraint FK9CE339F5CD710A51 
        foreign key (candidate1_id) 
        references CandidateJPA;

    alter table QuestionJPA 
        add constraint FK9CE339F5F86CEDC1 
        foreign key (tagLevel1_id) 
        references TagJPA;

    alter table QuestionJPA 
        add constraint FK9CE339F53ADE8F72 
        foreign key (candidacy_id) 
        references CandidacyJPA;

    alter table ResponseJPA 
        add constraint FKD188BFBA87A14762 
        foreign key (electeur_id) 
        references ElecteurJPA;

    alter table ResponseJPA 
        add constraint FKD188BFBAB35BA17C 
        foreign key (question_id) 
        references QuestionJPA;

    alter table StatsCandidacyJPA 
        add constraint FK2795E1523ADE8F72 
        foreign key (candidacy_id) 
        references CandidacyJPA;

    alter table StatsThemeJPA 
        add constraint FKCD9A32F1F5FB228E 
        foreign key (tag_id) 
        references TagJPA;

    alter table UserStatsJPA_StatsCandidacyJPA 
        add constraint FKB20BD2DA94D961D6 
        foreign key (statsCandidacy_id) 
        references StatsCandidacyJPA;

    alter table UserStatsJPA_StatsCandidacyJPA 
        add constraint FKB20BD2DA4EC62367 
        foreign key (UserStatsJPA_id) 
        references UserStatsJPA;

    alter table UserStatsJPA_StatsThemeJPA 
        add constraint FK49962879FF269694 
        foreign key (statsTheme_id) 
        references StatsThemeJPA;

    alter table UserStatsJPA_StatsThemeJPA 
        add constraint FK499628794EC62367 
        foreign key (UserStatsJPA_id) 
        references UserStatsJPA;
